name: Build executables

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          host: 'windows'

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Configure build
        run: cmake -B build -S Display  
      
      - name: Build
        run: cmake --build build --config Release

      - name: Copy executable to package folder
        run: |
          mkdir package
          copy build/Release/RoomBookerDisplay.exe package/

      - name: Package for Windows
        run: windeployqt6.exe package/RoomBookerDisplay.exe

      - name: Compile final installer
        run: |
          $env:PACKAGE_PATH="${{ github.workspace }}/package"
          iscc ${{ github.workspace }}/Display/setup.iss

      - name: Upload Windows Installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: Display/Output/RoomBookerDisplayInstaller.exe

  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'

      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Configure build
        run: cmake -B build -S Display  
      
      - name: Build
        run: cmake --build build --config Release

      - name: Copy files to package folder
        run: |
          mkdir package
          cp build/RoomBookerDisplay package/
          cp Display/resources/defaulticon.png package/
          cp Display/RoomBookerDisplay.desktop package/

      - name: Package for Linux
        run: linuxdeploy-x86_64.AppImage --executable=package/RoomBookerDisplay --output=appimage --plugin=qt --appdir package
      
      - name: Upload Linux AppImage
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: RoomBookerDisplay-x86_64.AppImage
